# Generated by Django 2.1.5 on 2021-08-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0003_auto_20210804_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Rate',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
