# Generated by Django 2.1.5 on 2021-08-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0004_auto_20210805_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='Date',
        ),
    ]
