# Generated by Django 2.1.5 on 2021-08-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0005_remove_comments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='Rate',
        ),
    ]
