# Generated by Django 2.1.5 on 2021-08-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0008_auto_20210805_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
    ]
