# Generated by Django 2.1.5 on 2021-08-06 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0010_auto_20210805_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='book',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='time',
        ),
    ]
